### ISSUE TITLE
Architecture draft specification (Frontend)

### ISSUE THREAD

**Issue by marektavac** [fri-team/Swapify#10]
We need to specify architecture as fast as possible. We know the technologies already, so some parts should be clear.
We need the first draft to be able to discuss it (what is clear, what not and we need to discuss - may be with some advice's )
It should contains list of tiers.
Also it would be good to have the draft of .sln structure depend on it.

**Comment by marektavac** [comment]
@fri-team , everybody is busy? Do you like it somebody? This task is important. I can help with personal consultation... @ZVARKO, may be the unit test can wait :-)

**Comment by marektavac** [comment]
@ikim23 said: celkom som neporozumel co si tym myslel. Uz sme sa zhodli viac menej na technologiach, jedine co nie je urcene je unit test framework pre .NET a databaza, co sa vyriesi este teraz, povedzme do piatku. Tiez vieme, ze budeme mat applikaciu strukturovanu ako API na serveri a react appka beziaca v prehliadaci. Co si predstavujes pod tym draftom?

**Comment by marektavac** [comment]
Ist viac do hlbky: React asi urci ze tam bude MVC => vrstva model, view, controller. Bude tam asi nejaka datova vrstva, nejake prenosove entity, nejake zapuzdrenie tych rozvrhov... Ako to budeme delit na dll, kde budu testy.... Kludne rad pomozem. Nepredpokladam, ze priamo v controleru alebo modelu budete pisat vsetok kod, ci sa pletiem?

**Comment by ikim23** [comment]
OK. I can write the React part. Someone else could take the backend part, or should I take it all?

**Comment by marektavac** [comment]
The final result (now the draft is OK) should be: .sln with projects and folders and everybody knows where and what to program :-)

**Comment by marektavac** [comment]
I can assist to anybody to consult...
