### ISSUE TITLE
Add new block to student timetable

### ISSUE THREAD

**Issue by davidm1766** [fri-team/Swapify#103]
Add combobox with filter for courses names (backend+frontend).
Display all courses which are in student timetable in left panel after click in the Predmet field (if simple to do), after some text insert filter regulary 
Autofill skratka predmetu after predmet selection (and oposite)
Profesor and room is not mandatory

AC:
actualize list of courses when new block with new course is added
showen timetable contains new block

**Comment by DenisaR1** [comment]
@martingranak  aký je aktuálny stav?

**Comment by martingranak** [comment]
After filling two or more latters to field "Course name" application show courses with same first latters.

**Comment by martingranak** [comment]
This week I repaired adding block to correct time. It was necessary to repair adding block of type "Excercise".

**Comment by mdomdo0** [comment]
FE refactored to redux. added block will be instantly showed in my timetable

**Comment by marektavac** [comment]
pekne, commit s ID issue a comment v issue pri presune review

**Comment by mdomdo0** [comment]
course shortcut is now a autofilled after course choose. room and teacher is no more required

**Comment by fri-team** [comment]
Done already
