### ISSUE TITLE
Implementation of the exchange

### ISSUE THREAD

**Issue by dobi28** [fri-team/Swapify#108]
After each exchange request, a compliance check is performed with requests already in DB. In case that a match is found, it is necessary to:
    -if several matches are found, choose the first one    
    -update the timetable for both students
    -on successful exchange request, set "successfully exchanged" flag in DB(for statistics) 
    -for other requests concerning these two students and the subject, set "unsuccessfully exchanged" flag in DB (for statistics)
    -notify both students about the exchange (possibly tell them, that other exchange requests regarding this subject, if any, were deleted)
In the case that no match is found, save request to DB.

**Subtasks**
#171 Design
#106 Backend

**Comment by marektavac** [comment]
Don't forget for concurency problem, may be some critical section should be used

**Comment by AdrianaVrtielova** [comment]
FINISH: Send e-mail about exchanged and notification in app.

**Comment by DenisaR1** [comment]
@marek1123  please make the chceckboxes with tasks

**Comment by marek1123** [comment]
tasks #225 and #226 where created from this issue
