### ISSUE TITLE
Timetable API questions to UIKT

### ISSUE THREAD

**Issue by marektavac** [fri-team/Swapify#13]
Please write all questions to UIKT about Timetable API a way, that Mr. Hrkut will just resend your questions:
- student timetable
- errors we found
- ???

Add @marektavac to email as cc.
Form it as clear as possible to minimize number of roundtrips
Due date: ASAP

**Comment by ikim23** [comment]
I think that API call `getUnizaScheduleContent.php` does not work when I search for timetable of the course:
```
getUnizaScheduleContent.php?m=4&id=5BA126%2C5%2C2%2C1
```
returns:
```
{
   "report": "Nenašli sa žiadne bloky pre rozvrh.",
   "ScheduleContent": []
}
```
even though at vzdelavanie it works as expected...

**Comment by davidm1766** [comment]
I sent mail and CC for @marektavac

**Comment by marektavac** [comment]
@davidm1766 , You have forgotten the question about possibility to get timetable for student (not a study group)

**Comment by davidm1766** [comment]
I wrote about missing timetable for student two weeks ago, but I will write email with request to implement timetable for student to public API

**Comment by davidm1766** [comment]
@ikim23 
Reply: This service has composed parameter witch you can get by calling getUnizaScheduleType4.php, subject code is not unique identifier

**Comment by ikim23** [comment]
Thanks. That means, we have incomplete API documentation on Confluence, because there is nothing about getUnizaScheduleType4.php (or 2,3). Please, add there some info + examples.
Anyway, I tried to put value from getUnizaScheduleType4.php as id to getUnizaScheduleContent.php and it still does not work 👎 .
