### ISSUE TITLE
Attach timetable to real data

### ISSUE THREAD

**Issue by mdomdo0** [fri-team/Swapify#142]
Attach timetable to real data

**Comment by martingranak** [comment]
It was necessary to connect side panel with checkboxes which course timetable is showed.
Course timetable is showed after check. Course blocks which not exist in actual timetable have pale color.
Course timetable is loaded only from our database. 
It is necessary to check posibilities with schoole API.

**Comment by martingranak** [comment]
![obrazok](https://user-images.githubusercontent.com/36951083/53757277-902a2b80-3ebb-11e9-8283-46840209bd83.png)

**Comment by marektavac** [comment]
The goal is: show all blocks of switched on course

**Comment by DenisaR1** [comment]
@martingranak  what is the status of this task?

**Comment by fri-team** [comment]
Done already
