### ISSUE TITLE
Fix lecture view

### ISSUE THREAD

**Issue by dobi28** [fri-team/Swapify#144]
The problem occurs when viewing lectures presented by more than 1 lecturer with duration of more than 2 hours... The lecture block is split after each hour. 
This block needs to be displayed as a whole rather than being split-up.

**Comment by marektavac** [comment]
It woold be good, to write also the guide how to get to this error and a picture of the situation if you have some... (it will help somebody to solve and understand this problem also after longer time

**Comment by fri-team** [comment]
Done already
