### ISSUE TITLE
Provide the current status of API

### ISSUE THREAD

**Issue by DenisaR1** [fri-team/Swapify#145]

**Comment by marektavac** [comment]
@DenisaR1 No description. What for API? Why? What is the problem? Will you understand this task after 2 month?

**Comment by marektavac** [comment]
API is more clear after communictaion with Mr. Malacky...
It is possible to specify year and term.
It is also possible to ask for students timetable.
I have inserted the specification to https://nike.kst.fri.uniza.sk:9443/display/SWAP/Timetable+API+Documentation
