### ISSUE TITLE
Display choosen exchanged blocks in colors and your timetable in shadow

### ISSUE THREAD

**Issue by DenisaR1** [fri-team/Swapify#149]
After click on the icon of exchange the timetable will dispalyed  in colors.

**Comment by mdomdo0** [comment]
![image](https://user-images.githubusercontent.com/18125162/53756983-cadf9400-3eba-11e9-8003-f1a5f3787d64.png)

after select excange course. course willbe colored but rest of timetable got opacity .... same funcion is applied to choose course timetable

**Comment by AdrianaVrtielova** [comment]
#142

**Comment by fri-team** [comment]
Already done
