### ISSUE TITLE
Link the existing exchange to exchange panel

### ISSUE THREAD

**Issue by DenisaR1** [fri-team/Swapify#150]
Existing exchange must be displayed in exchange panel 

![image](https://user-images.githubusercontent.com/34597942/54427634-59ee7680-471b-11e9-9815-097a0521455e.png)

Exchange panel (element 1) should show all waiting exchange requests of actual user. 

**Acceptation criteria:**

1. Exchange panel shows all waiting exchanges.
2. When user makes new exchange request and the exchange can not be immediately made, the exchange panel is updated to show new waiting exchange request.
3. Automatic updating when data on back-end is changed (another user makes exchange request and request is made) is not required for this task.

**Comment by marek1123** [comment]
![image](https://user-images.githubusercontent.com/34597942/54427634-59ee7680-471b-11e9-9815-097a0521455e.png)

Exchange panel (element 1) should show all waiting exchange requests of actual user.

**Comment by marek1123** [comment]
@DenisaR1 what information do we want to show for each exchange, same information as is shown in screenshot in task description ? Is it the name of the course and information (day and time) for the block to which we want to change.

**Comment by DenisaR1** [comment]
@marek1123  yes , I think the name of the course and information are enough

**Comment by fri-team** [comment]
Already done
