### ISSUE TITLE
Prepare staging server

### ISSUE THREAD

**Issue by DenisaR1** [fri-team/Swapify#152]
@mdomdo0 please write here what is goal of this task , how you want to make it, what are the options

**Comment by AdrianaVrtielova** [comment]
Please write current status of this task.

**Comment by martingranak** [comment]
Now I try deploy application on Heroku. Heroku allow user to work with docker and github. 
If this does not work I will try deploy application on server on FRI.

**Comment by martingranak** [comment]
I found better solution, Azure. Azure is devepoled by Microsoft so it has better support for C# application as Heroku. There is possible to set autodeploy function.

**Comment by martingranak** [comment]
This week I tried deploy little app using docker and docker compose. I found out that heroku hasn't support for multi-container application. There can be problem with file database in containet so I recommend to use server database.

**Comment by martingranak** [comment]
Application is ready to be deployed on server.

**Comment by marektavac** [comment]
Server should not be problem, it is preparing...
