### ISSUE TITLE
Wrong block merge

### ISSUE THREAD

**Issue by marektavac** [fri-team/Swapify#154]
There is one more problem with block merging. As you can see on picture, one and the same subject is in the same time and place (probably just teacher is different). 
I suggest, that if place and time and subject is the same, it is the same block (especialy if it is lecture)
![image](https://user-images.githubusercontent.com/37049814/53798151-ee94ef80-3f37-11e9-95a5-5e17b56bd019.png)

Related to #144 

AC: The same blocks will be merged in one block in DB and GUI

**Comment by marek1123** [comment]
**Question:**
Do we want to keep all teacher names or only the one name (of the first for example).

**Comment by marektavac** [comment]
They can be merged, separated by comma

**Comment by fri-team** [comment]
Already done
