### ISSUE TITLE
Add new exchange request

### ISSUE THREAD

**Issue by marek1123** [fri-team/Swapify#159]
**Actual state (Done):**
![image](https://user-images.githubusercontent.com/34597942/54429281-59a4aa00-4720-11e9-9618-27a3837126a2.png)

User clicks button for exchange (element 1 / View 1).

![image](https://user-images.githubusercontent.com/34597942/54429258-4db8e800-4720-11e9-99c1-819ee2de74d0.png)

Change of the view to View 2.

**TODO:**

When user clicks block (element 2 / View 2) new exchange request (for exchange between block 
( element1/View1) (student actually has) and block (element2/View2) (student wants)) is made.
If another exchange request from block (element2/View2)(another student has) to block (element1/View1) (another student wants) exists, exchange is done. Show information (to user), if exchange was done or only added with status waiting.

**Acceptation criteria**
1. When user requests exchange and there is no corresponding request for exchange from other user request for exchange is saved (information that request was created and saved with status waiting is showed in popup window) and showed in sidebar.
2. When user A requests exchange and there is corresponding request for exchange from the user B  request for exchange from user A is saved with status DONE, status of request for exchange from user B is set to DONE and other requests for exchange from users A and B for just exchanged blocks are canceled. Information that request was created and saved with status DONE is showed in popup window and sidebar is updated.

**SUBTASKS**
frontend - #174

**Comment by marek1123** [comment]
Actual state:
![image](https://user-images.githubusercontent.com/34597942/54428702-92dc1a80-471e-11e9-85a4-0168d421761e.png)

User clicks button for exchange (element 1).

**Comment by marek1123** [comment]
![image](https://user-images.githubusercontent.com/34597942/54428865-24e42300-471f-11e9-9858-2923a79f7a26.png)

Change of the view to State 2.

**Comment by marektavac** [comment]
Nice, we can use it as example of feature issue?

**Comment by marek1123** [comment]
I updated the description of the task with acceptation criteria. It could probably serve as example for feature task. There are still points relevant to acceptation criteria which should be discussed. E. g. the part **"Actual view of student's timetable has not to be automatically updated after another user makes exchange"**, we should decide if this is true for this task. Same for the point that you made **"will be there some change of GUI, or some message that the request was saved and waiting for exchange?"**.

**Comment by DenisaR1** [comment]
@marek1123  Marek pls think about some window with question like "Are you sure that you want to cancel this?" or some another "escape button"

**Comment by fri-team** [comment]
Already done
