### ISSUE TITLE
Frontend for exchange panel

### ISSUE THREAD

**Issue by marek1123** [fri-team/Swapify#162]
Implement frontend for feature #150 .

Add new endpoint for getting all user waiting exchange requests (to the api.js).
Modify store to contain data for user waiting requests (design the form of data in store, create reducer).
Decide when the data should be populated (when application starts or when the sidebar with list of exchange requests is first opened) and eventually create suitable actions and the thunk or saga for making the api call. Pass store data for exchange requests to SidebarContainer.js. Pass data from SidebarContainer.js to Sidebar.js. Design the view of individual list elements (one element for one exchange request) and show exchange requests. Implement test for reducers.

TODO: implement test for reducers

**Comment by marek1123** [comment]
Test data returned from api endpoint does not contain BlockFrom and BlockTo. [Backend] Block contains only id of course. If we want to show course name, api endpoint should take that into account and find course with defined id and return it with ExchangeRequest data.

**Comment by fri-team** [comment]
Already done
