### ISSUE TITLE
Create welcome page

### ISSUE THREAD

**Issue by AdrianaVrtielova** [fri-team/Swapify#165]
- [x] Prepare first design for welcome page. The welcome page should include following:
- detail information about Swapify project
- a few screenshots from app
- note about cooperation with Globallogic and logo
- join us (opportunity to join us for new students)
- first registration and log in to app
- contact, support, help

- [x] Create the welcome page based on provided design.

**Comment by DenisaR1** [comment]
@mdomdo0  please create first mockup for welcome page.

**Comment by marektavac** [comment]
From opening page should be immediately clear what profit will get the student, when he will register (nice personal timetable, editable - add missing block, change wrong block, delete; support for block exchange - simple find possible blocks, auto contact for exchange if found any, ...).

**Comment by mdomdo0** [comment]
![image](https://user-images.githubusercontent.com/18125162/59906072-08374580-9408-11e9-810c-794835128060.png)

![image](https://user-images.githubusercontent.com/18125162/59906091-1a18e880-9408-11e9-9081-ce2c721874d4.png)


![image](https://user-images.githubusercontent.com/18125162/59906112-2bfa8b80-9408-11e9-92bc-57c3df0df16a.png)

**Comment by fri-team** [comment]
Already done
