### ISSUE TITLE
Remove study group

### ISSUE THREAD

**Issue by marek1123** [fri-team/Swapify#168]
**Current state**
Currently we register study group of student. Study group id is used to find the timetable of study group. Timetable of study group is used to create initial timetable of student in database.

**TODO**
API used to query timetable of study group can return directly timetable of student. Application should be modified to query the timetable of student (identified by personal id). The timetable of student received from API should be used to create initial timetable of student in Swapify database. 
Changes which should be done on **backend** and **frontend** to implement the change should be analysed.

**SUBTASKS**
#169 frontend
#170 backend

**Comment by marektavac** [comment]
I like list of subtask :-)

**Comment by fri-team** [comment]
Already done
