### ISSUE TITLE
Remove study group on frontend

### ISSUE THREAD

**Issue by marek1123** [fri-team/Swapify#169]
subtask of #168 issue

Implement changes on frontend which follow from changes specified in task #168.

**Current state**
1. User logs in first time.
![Screenshot (40)](https://user-images.githubusercontent.com/34597942/55616680-a2d1a200-5792-11e9-8f68-8e7104136bc0.png)

2. User has to specify the study group id (on first login).
![Screenshot (42)](https://user-images.githubusercontent.com/34597942/55616663-99e0d080-5792-11e9-95c5-cefd3cd9d343.png)

3. Timetable of specified study group is used to create student timetable which is than showed to user.
![Screenshot (44)](https://user-images.githubusercontent.com/34597942/55616901-2e4b3300-5793-11e9-9f06-a05c44ac3b64.png)

**TODO**
Step 2 (see part Current state) will be removed. As timetable used to create initial timetable of the user after first login will be used directly timetable (received from uniza-timetable-API) of student.

**Comment by marek1123** [comment]
**CURRENT STATE**
User can change the study group (see button Zmeniť skupinu).
![Screenshot (45)](https://user-images.githubusercontent.com/34597942/55617436-5d15d900-5794-11e9-9203-361d88546bdb.png)

**TODO**
Option to change the study group shoud be removed.

**Comment by marektavac** [comment]
@marek1123 very nice. Probably register will be changed (student id will be added)...

You said:
"As timetable used to create initial timetable of the user after first login will be used directly timetable (received from uniza-timetable-API) of student." - we should calculate with problem of TAPI, or wrong student id (or change). So we should enable to user change his/her personal data (email, **student id**, ...) May be this dialog could be activated throuch "change group" - replace it...
I would add there also button for "reload my tinmetable" to this dialog (my profile), to solve the problems from above or to reset my wrong changes...

**Comment by marek1123** [comment]
Yes I see that if we remove dialog for setting the study group ID there is no place in application, or step during registration where we set the Student ID, so we should probably modify the dialogs where we set the study group ID to accept student ID instead. But we should also discuss if the user should be able to set any Student ID (for example student ID of other student).

**Comment by fri-team** [comment]
Already done
