### ISSUE TITLE
Remove study group on backend

### ISSUE THREAD

**Issue by dobi28** [fri-team/Swapify#170]
subtask of #168 issue

Implement changes on backend which follow from changes specified in task #168.

**Current state**
After first user log he need to specify his study group. Our API provide him timetable for this group and save it as his own.

**Comment by martingranak** [comment]
Study group was removed from BE and from FE too. I changed it for student number.
Now application shows current timetable for student number that has been set.
I attach some pictures.
![obrázok](https://user-images.githubusercontent.com/36951083/58369154-dd37ff80-7ef6-11e9-99f2-94824716ec1f.png)

**Comment by fri-team** [comment]
Already done
