### ISSUE TITLE
Proposal exchange e-mail

### ISSUE THREAD

**Issue by dobi28** [fri-team/Swapify#171]
subtask of #108 issue

Propose text which send users after successfully exchange. Also consider template look. Currently template looks like this:

![image](https://user-images.githubusercontent.com/43958473/55620079-4e322500-579a-11e9-9a70-34914c5ede2b.png)

**Comment by DenisaR1** [comment]
Hi Mato, I suggest the same template (maybe there will be new logo from Dominik) and the text : " Tvoja výmena prebehla úspešne." "Ak si chceš pozrieť viac informácií o tvojej výmene prihlás sa, alebo klikni na odkaz."

**Comment by DenisaR1** [comment]
Something like this 

![55620079-4e322500-579a-11e9-9a70-34914c5ede2b](https://user-images.githubusercontent.com/44035752/56495734-f49a5c00-64f6-11e9-9941-857d245ad3aa.png)

**Comment by marektavac** [comment]
Ahojte

 

Neviem ci to je postacujuce...

Podla mna ziadna vymena neprebehla... Len sa nasiel niekto kto sa chce vymenit...

Vymeny si uz musia zabezpecit sami....

 

 

--

S pozdravom

Ing. Marek Tavač, PhD.

Katedra softvérových technológií

Fakulta riadenia a informatiky

ŽU Žilina

+421 41 5134130

**Comment by DenisaR1** [comment]
@marektavac  ok, I will change the text about the change

**Comment by DenisaR1** [comment]
![nav11](https://user-images.githubusercontent.com/44035752/56578636-685b6800-65ce-11e9-9cd0-51f20ec68208.jpg)

**Comment by DenisaR1** [comment]
![nav2](https://user-images.githubusercontent.com/44035752/56578664-77dab100-65ce-11e9-8507-e2a4c47c65b7.jpg)

**Comment by DenisaR1** [comment]
@dobi28  look at this pls

**Comment by dobi28** [comment]
I changed the template and now it looks like this

![obrázok](https://user-images.githubusercontent.com/43958473/68329793-548ed380-00d2-11ea-932d-9654ae2eb1e0.png)

I also added a new template and some logic regarding the sending of mail to notify students about a successful exchange.

**Comment by fri-team** [comment]
Already done
