### ISSUE TITLE
Add new exchange request on frontend

### ISSUE THREAD

**Issue by marek1123** [fri-team/Swapify#174]
frontend for task #159 

**Current state**

1. After clicking on exchange button in BlockDetail component (src\components\BlockDetail\BlockDetail.js) exchangeRequest(course) method is called.

2. In exchangeRequest(course) action function showExchangeModeTimetable(course) (from src\actions\timetableActions.js) is called. 

3. In showExchangeModeTimetable() function dowloadCourseTimetableIfNeeded() is called.

4. dowloadCourseTimetableIfNeeded returns thunk action

5. if needed, dowloadCourseTimetableIfNeeded thunk action make API call to get course timetable (if API call fails saved timetable from .json file is used)

6. action SHOW_COURSE_TIMETABLE is dispatched

7. timetableReducer (src\reducers\timetableReducer.js) processes action (showed timetable is modified, timetable.blockFromExchange nor timetable.isExchangeMode is set)

**TODO:**

- [x] update displayed timetable in the case that the exchange was made
- [x] show notification (popup window informing if exchange was made)

**Comment by marek1123** [comment]
How to stop the process of request for exchange creation (e.g. in moment after clicking the echange button when only blocks of course are dispalyed) ? -> Already solved. Button up, right (Return to timetable).

**Comment by fri-team** [comment]
Already done
