### ISSUE TITLE
Show course timetable from API

### ISSUE THREAD

**Issue by martingranak** [fri-team/Swapify#182]
Current state:
- application show only course timetable from our database

Required state:
- application will show course timetable from API and will save it to our database if timetable is not actual.

**Comment by marektavac** [comment]
Good idea, to save it, I suggest that if you are not able to connect and download actual timetable, it will be used database one. Or not?

**Comment by marektavac** [comment]
Z UIKT mi potvrdili , ze sa na tie nazvy predmetu pozru, ale asi to nebude hned... Mame zatial nejake alternativne riesenie? Zeby sa napr. nazvu zatial zobrazovalo cislo? (nahra sa do nazvu) a neskor by sa to uz len prehodilo...

**Comment by martingranak** [comment]
Course timetable is loading by change of personal number and block adding.
1. step: loading of information about course
2. step: loading of course timetable

**Comment by fri-team** [comment]
Already done
