### ISSUE TITLE
Timetable is not showing all blocks

### ISSUE THREAD

**Issue by marek1123** [fri-team/Swapify#183]
Not all blocks in timetable are displayed.

As is:
![image](https://user-images.githubusercontent.com/34597942/59587661-13c3fd00-90e6-11e9-90ca-2aeb10aa3f2e.png)

As should be:
![image](https://user-images.githubusercontent.com/34597942/59587691-2807fa00-90e6-11e9-8f79-f48450bb0f36.png)

**Comment by fri-team** [comment]
Already done
