### ISSUE TITLE
Pick Unit test framework for .NET Core

### ISSUE THREAD

**Issue by ikim23** [fri-team/Swapify#2]
Subtasks:
- [x] Find suitable framework for writing init test
- [x] Create at least one demo test
- [x] Add test run to CI

Also see tools recommended by @marektavac:
* [moq](https://github.com/moq/moq4)
* [fluent assertions](http://fluentassertions.com/)

**Comment by ikim23** [comment]
@ZVARKO write here your progress. So far we know you picked up XUnit framework. Please, create pull request with stuff that you done so far, so we all can see your progress. Thanks.

**Comment by marektavac** [comment]
If it is finished, please move it to done
