### ISSUE TITLE
Show actual student timetable

### ISSUE THREAD

**Issue by bohusmarian** [fri-team/Swapify#21]
Display actual (basic) student timetable from database (with already accepted changes)
Every subject will have its own color.
It should be clear:
- it is Labak, Cvicenie or prednaska (prednaska may be stronger color)
- course name
- room number
- teacher name
Solve problem how to show conflicted courses

ToDo:
- [ ] On the backend site just load manually inserted data and give it to Fronted (use actual domain structures)
- [ ] Check and repair domain objects
- [ ] API specification
- [ ] Fronted

![timetable](https://user-images.githubusercontent.com/37049814/38089055-6fc12434-335e-11e8-9c07-c2ff16898691.png)
But axes are reverted

**Comment by ikim23** [comment]
* differentiate courses by applying color
* add transparency to courses that are not mine
* add margin-top to overlapping blocks
![swapify](https://user-images.githubusercontent.com/22031712/38456272-447d9cd6-3a83-11e8-9d0d-aac8387e2704.png)

**Comment by marektavac** [comment]
So may be we should return to less colors :-( we have to discuss it)
