### ISSUE TITLE
View the timetable of one subject

### ISSUE THREAD

**Issue by DenisaR1** [fri-team/Swapify#210]
Timetable of selected subject should be showed when requested.

**Comment by mdomdo0** [comment]
fixed switcher on sidebar to show subject timetable

**Comment by matasovskyd** [comment]
merged to develop

**Comment by brano98** [comment]
Timetable of subject should be showed when requested.

**Comment by Malwaare** [comment]
In DB save timestamp for the subject timetable. When a user requests to show a specific timetable, look at the timestamp first, if it's older than 2 days, make an API call for the subject first to save it into DB then show it to the user.

**Comment by BranislavTvrdy** [comment]
We have to chose scenario for "When a user requests to show a specific timetable". Either:
- [ ] User opens sidepanel and choses to show specific timetable for subject he already has.
or
- [ ] User is adding new subject to timetable and is given the option to see timetable of given subject to possibly choose one of the blocks already described by its timetable.
