### ISSUE TITLE
Add certificate (lets encrypt)

### ISSUE THREAD

**Issue by DenisaR1** [fri-team/Swapify#222]
It can be used also some other solution (depend on AWS and docker support)

**Comment by MarekZorvan** [comment]
![image](https://user-images.githubusercontent.com/43585019/80391369-ee7b5000-88ad-11ea-9245-8af7d2032a86.png)

Let's encrypt won't issue certificate for bare Ip address, which we will have with AWS VM without registered domain. Maybe there is option to have some free aws subdomain like MS Azure has, but that's unlikely.

**Comment by MarekZorvan** [comment]
We have our domain swapify.fir.uniza.sk now :) 

SSL certificate will be added in upcoming days to our AWS server.

![image](https://user-images.githubusercontent.com/43585019/98667041-2af43200-234e-11eb-88ed-2ced03b1bf96.png)

**Comment by marektavac** [comment]
Perfect, but fri not fir :-)

**Comment by marektavac** [comment]
Is http://swapify.fri.uniza.sk/ already our server on AWS?
When I try:
ping or nslookup I get IP: 158.193.143.53

**Comment by MarekZorvan** [comment]
Yes, you are right. It's just that old address 158.193.143.53 works now again. It.wasn't even accessible as swapify application for quite a long time. 


So we still don't have our domain for.current IPv4 address. :(

**Comment by MarekZorvan** [comment]
Let's encrypt are created on our AWS EC2, but are not used, since only apache or nginx server can use them.

branch #317 has prepared nginx.conf and some https .NET code ready, but is started by .NET CLI on AWS now, which doesn't have SSL certificates for https.

**Comment by Malwaare** [comment]
Done
