### ISSUE TITLE
Create integration tests for exchange

### ISSUE THREAD

**Issue by marek1123** [fri-team/Swapify#224]
Create integration test for exchange according to the following test scenario (see project folder Tests/IntegrationTests):

**Precondition**:
- COURSE1 is saved in database
- 2 users (USER1, USER2) with course COURSE1 in time TIME1 (USER1) and TIME2 (USER2) is saved in database

**Test steps**:
Action1: USER1 creates exchange request for COURSE1 from TIME1 to TIME2
Result1: exchange request REQUEST1 is saved in database (in state WAITING)

Action2: USER1 creates exchange request for COURSE1 from TIME1 to TIME3
Result2: exchange request REQUEST2 is saved in database (in state WAITING)

Action3: USER2 creates exchange request for COURSE1 from TIME2 to TIME1
Result3: exchange request REQUEST3 is saved in database (in state DONE), state of REQUEST1 is updated to state DONE, REQUEST2 is deleted

**Notes**
Consider dividing Test steps to multiple tests.

**Comment by fri-team** [comment]
already dona
