### ISSUE TITLE
Exchange request found notification

### ISSUE THREAD

**Issue by marek1123** [fri-team/Swapify#225]
**Current state**
When corresponding exchange request of another user is found (see #159 for information on exchange process) new notification with simple text is created and saved in database. Notifications are fetched from server and showed in notification panel on front-end.

**TODO**
Analyse what information should be showed in exchange notification. Analyse possibility of linking exchange notification in notification panel with corresponding exchange request in sidebar (user clicks notification in notifications panel, sidebar with exchange requests is opened and corresponding exchange request is highlighted). Implement result of analysis and eventually create more tasks (in case of implementing linking of sidebar with exchange reqeusts with notifications, changes in sidebar would be required because it only shows waiting exchange requests).

**Comment by marektavac** [comment]
This task is needed to update.
