### ISSUE TITLE
Switch course name and course code

### ISSUE THREAD

**Issue by mdomdo0** [fri-team/Swapify#241]
Switch course name and course code to temporary fix missing course names from timetable api.

**Comment by marektavac** [comment]
They fixed the web servives from UIKT, please try them if it is already OK, may be this task is not anymore necessary to do...
Changed services:
   getUnizaScheduleContent.php
   getUnizaScheduleType.php
   getUnizaScheduleType2.php
   getUnizaScheduleType3.php
   getUnizaScheduleType4.php

**Comment by dobi28** [comment]
Looks like it's fixed. The parameter "s" contains the course name for the API calls according to the student personal number and the subject id.

**Comment by marektavac** [comment]
Thanks for feedback...

**Comment by fri-team** [comment]
already done
