### ISSUE TITLE
Upgrading to React v16.8.0 - refactor unsafe lifecycles

### ISSUE THREAD

**Issue by MarekZorvan** [fri-team/Swapify#242]
Upgrading react & react-dom to v16.8.0 was necessary for some issue #205 functionality.
Code refactoring for removal of warnings and preparation for React 17.x async rendering.

![image](https://user-images.githubusercontent.com/43585019/69493781-4652fc80-0eb3-11ea-92e4-370055762d44.png)

**Comment by MarekZorvan** [comment]
![image](https://user-images.githubusercontent.com/43585019/72667633-3f151e80-3a1e-11ea-930f-c01733718e49.png)

React & necessary packages updated. FE works without any serious warnings.

**Comment by fri-team** [comment]
already done
