### ISSUE TITLE
Create "Mail Us" functionality 

### ISSUE THREAD

**Issue by reibek** [fri-team/Swapify#247]
Just integrate backend with frontend...

Point is to create functionality, that will provide user option to send us some kind of feedback.

**Comment by marektavac** [comment]
Please contact @matasovskyd , he is analysing similar think witn Sentry... To not implement it twice...

**Comment by reibek** [comment]
Actual state is, that integration of BE and FE is needed to work functionality correctly.

**Comment by MarekZorvan** [comment]
@reibek check the status of this issue

**Comment by MarekZorvan** [comment]
Send email to all developers(uses swapifyteam@gmail.com atm) for now?

**Comment by marektavac** [comment]
Is somebody checking this email? Our common mail is swapify@kst.fri.uniza.sk. I can ask to create special mail with the same domain, but somebody should monitor it...

**Comment by marektavac** [comment]
I have an idea, we can make special channel (e.g. mailUs) in MS-teams, and redirect all mail there. So everybody will see imediately every message from user... Problem is, that this email address is not very nice (like: `General - edu-fri-swapify <0f4e1dad.uniza.sk@emea.teams.ms>`). But it is possible to create swapify-mail-us@kst.fri.uniza.sk and redirect everythink from there to this channel...

It will look in the channel like this:
![image](https://user-images.githubusercontent.com/37049814/96276745-b1c62100-0fd3-11eb-9a70-075ad45f0149.png)

**Comment by reibek** [comment]
Feature was tested and improved (#386) and it's working. Currently email for feedback is set for swapifyteam@gmail.com, but can be easily changed in mailing settings in `appsettings.json`. 

Example of an email:

![swapify_mailing2](https://user-images.githubusercontent.com/46252411/96525071-481b7080-127a-11eb-839d-24fd9fd19a7a.PNG)
