### ISSUE TITLE
Corrupted visual when showing course blocks

### ISSUE THREAD

**Issue by marek1123** [fri-team/Swapify#250]
Timetable before showing the course blocks:
![image](https://user-images.githubusercontent.com/34597942/70866364-0a1e3380-1f69-11ea-8225-34f2adb313c4.png)

Timetable after showing the course blocks:
![image](https://user-images.githubusercontent.com/34597942/70866369-24581180-1f69-11ea-9164-26f722d649fa.png)

Timetable after hiding the course blocks:
![image](https://user-images.githubusercontent.com/34597942/70866386-55384680-1f69-11ea-8fb7-48952888a0a6.png)

**Comment by marektavac** [comment]
Fixed in other task.
