### ISSUE TITLE
Deploy hotfix - unite error and validation messages

### ISSUE THREAD

**Issue by mdomdo0** [fri-team/Swapify#253]
there are different formates of error and validation messages in login and registration like wrong email format etc... (example in dialog for change personal number)

-  unite login error and validation messages 
-  unite registration error and validation messages 

![obrázok](https://user-images.githubusercontent.com/37011575/72222412-adf90000-3564-11ea-9e39-b4cd5dcff9b6.png) - valid after click outside

first type of message
![obrázok](https://user-images.githubusercontent.com/37011575/72222422-c8cb7480-3564-11ea-834d-6df2c5ed8381.png)

second type of message (better, but error message under email/pasword text field)
![obrázok](https://user-images.githubusercontent.com/37011575/72222435-ef89ab00-3564-11ea-8d36-94d514dbb42c.png)
![obrázok](https://user-images.githubusercontent.com/37011575/72222449-13e58780-3565-11ea-872f-388114f167b9.png)

**Comment by fri-team** [comment]
already done
