### ISSUE TITLE
Deploy hotfix - Edit Block

### ISSUE THREAD

**Issue by mdomdo0** [fri-team/Swapify#254]
there are bugs in editing blocks.

- wrong overlay after course edit
- sometimes block isnt edited but copied and created as new block
- refresh page make appear old block

this is timetable for number (558855)
![obrázok](https://user-images.githubusercontent.com/37011575/72222508-82c2e080-3565-11ea-8ef5-be96609d1abe.png)

I worked with block in wednesday at 8:00. I changed start to 10:00 (it works), but if I changed day to thursday, new block was added but old was not removed. Change of block length creates other block too.
![obrázok](https://user-images.githubusercontent.com/37011575/72222556-5a87b180-3566-11ea-9e8f-4488949720f1.png)

**Comment by martingranak** [comment]
Fixed. There was two requests. First for remove block and second to add block. I created only one request to edit block. I added id to class Block, so I had to change logic of remove block and switching of courses timetable.

**Comment by fri-team** [comment]
already done
