### ISSUE TITLE
Deploy hotfix - Add block

### ISSUE THREAD

**Issue by mdomdo0** [fri-team/Swapify#255]
- autocomplete isnt working, we are not able to add course without course name
- increase range of course length
- close modal cross is on left side...

**Comment by martingranak** [comment]
Fixed. There was more problems.
1. After every application start were added courses to database (duplications)
2. Searching only on start of course name
3. Searching was case-sensitive (I tried remove diacritics too, but I did not found some good solution)

**Comment by fri-team** [comment]
already done
