### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by bohusmarian** [fri-team/Swapify#26]
Student enters email address, name and surname.
We will not use password for this moment. If it will be too annoying we will add it later.
@ikim23 please, add here what service we should you ASAP.
Then system send verification email to students email address and show info about sending verification email.
TODO:
- [x] Take sender's email from config file  
- [x] Register button on home page
- [x] Register form (validate input)
- [x] CRUD methods for user
- [x] Verify user email - send verification email
- [x] Verification page (confirmation of successful registration) with start button for timetable initialisation 
- [x] Add field to user class (verified, role), update domain model

**Comment by marektavac** [comment]
We can start to do this task. @ZVARKO do you can realize it? @ikim23 has some ideas how it could be done, please discuss it with him. 
@bohusmarian please add description to this task ASAP.

**Comment by marektavac** [comment]
The simplest solution is to use https://www.mailgun.com/pricing for our mail resending... Is it OK?

**Comment by DenisaR1** [comment]
@ZVARKO  what is status of this task?
