### ISSUE TITLE
Frontend corrections

### ISSUE THREAD

**Issue by martingranak** [fri-team/Swapify#268]
1. [x] Remove hamburger button for side bar on personal number change
![obrázok](https://user-images.githubusercontent.com/36951083/73529094-5983ca80-4416-11ea-9b17-55a964fd2dc8.png)
2. [x] Add onClickOutside action for notification bar
3. [x] Add anchor to user account text too (not only icon)
![obrázok](https://user-images.githubusercontent.com/36951083/73529238-abc4eb80-4416-11ea-869a-9146a27f5e88.png)
4. [x] Timetable of course is displayed after click on some block on exchange but shadowing is removed. Remove course timetable too. (tested on personal number 558855 and 558888)
5. [x] Rename labels on buttons from "predmet" to "blok"
![obrázok](https://user-images.githubusercontent.com/36951083/73529882-bfbd1d00-4417-11ea-9db8-5a021d7706e4.png)
![obrázok](https://user-images.githubusercontent.com/36951083/73529908-c8adee80-4417-11ea-9207-390f6166c62d.png)
6. [ ] After onClickOutside by every element (addBlockForm, notification bar, side bar) on timetable do not add block
7. [x] Button "Späť na rozvrh" is too big. Try to make it smaller and maove this button little to the left

**Comment by fri-team** [comment]
already done
