### ISSUE TITLE
Send email after block exchange

### ISSUE THREAD

**Issue by martingranak** [fri-team/Swapify#269]
1. There is not template for exchange confirm email.
- Try create similar template as registration confirm email.
2. Emails are not send to users, because there is problem with email server.
- Analyze other methods to send email from dotnet.

**Comment by dobi28** [comment]
1. Point is solved in "feature/269-Send_email_after_block_exchange" branch

**Comment by dobi28** [comment]
I solved 1. point

**Comment by fri-team** [comment]
already done
