### ISSUE TITLE
Width of side panel

### ISSUE THREAD

**Issue by martingranak** [fri-team/Swapify#270]
There is problem with long course name by course switching
![obrázok](https://user-images.githubusercontent.com/36951083/73568717-477f4780-4469-11ea-9bf0-fc7e4be1dacd.png)
and by exchanges too.
![obrázok](https://user-images.githubusercontent.com/36951083/73568765-5e259e80-4469-11ea-96c0-8e104b501ce3.png)
There is more good solutions:
1. corse name to more rows
2. if course name is longer then side panel width add "...". Mouse hover action will show full name.

**Comment by reibek** [comment]
Problem should be fixed in Pull Request #284
