### ISSUE TITLE
Message after creating of exchange

### ISSUE THREAD

**Issue by martingranak** [fri-team/Swapify#271]
After creation of exchange is shown message "Výmena bola vykonaná". 
This message will be shown after successful exchange. 
If is message only saved, show message "Žiadosť o výmenu bola prijatá"
If there is another problem, show error message "Pri vytváraní žiadosti nastala chyba"

**Comment by martingranak** [comment]
I recomend work on this issue after issue #269 Send email after block exchange

**Comment by fri-team** [comment]
already done
