### ISSUE TITLE
Useless texts in block detail

### ISSUE THREAD

**Issue by martingranak** [fri-team/Swapify#272]
On block detail is default texts.
![obrázok](https://user-images.githubusercontent.com/36951083/73569981-c6757f80-446b-11ea-97e9-415d3527b70c.png)
Try to find out way to show correct information of block detail or remove these texts.

**Comment by MarekZorvan** [comment]
![image](https://user-images.githubusercontent.com/43585019/73872966-fd270d80-4850-11ea-9ea2-f7713478cd49.png)

![image](https://user-images.githubusercontent.com/43585019/73873019-162fbe80-4851-11ea-9176-76cb45180f22.png)

**Comment by fri-team** [comment]
already done
