### ISSUE TITLE
Exchanges in block detail

### ISSUE THREAD

**Issue by martingranak** [fri-team/Swapify#273]
In block detail is default shown information about exchange.
![obrázok](https://user-images.githubusercontent.com/36951083/73570376-92e72500-446c-11ea-9bcb-3e398a6fb408.png)
Remove this text and try to show exchanges of this block.
There is more ways to show exchanges:
1. way (there is problem with more exchanges)
Výmeny:
- 10 00 pondelok 
- 12 00 utorok
2. way (worse desing)
Vymieňam za pondelok 10 00, utorok 12 00, ("..." if too much)
3. way - combination

**Comment by marektavac** [comment]
@PetraKinder think it is done. What is the actual state?
