### ISSUE TITLE
About us

### ISSUE THREAD

**Issue by martingranak** [fri-team/Swapify#274]
- [x] 1. Add space before first row.

- [x] 2. Add space between blocks

- [x] 3. Add logos of university, GlobalLogic, maybe faculty too

- [x] 4. Highlight main words

- [ ] 5. Change button About us to schitcher

**Comment by martingranak** [comment]
![Image from iOS](https://user-images.githubusercontent.com/36951083/73571364-a85d4e80-446e-11ea-8841-df1fe54e66fe.png)
![Image from iOS2](https://user-images.githubusercontent.com/36951083/73571372-aabfa880-446e-11ea-8a39-7e6a1d30c188.png)
There are logos of GL. Marek, please, can you find some actual .png logos of faculty or university?
Peťa, please, write there which words should be highlighted.

**Comment by BranislavTvrdy** [comment]
Here are the Faculty logos in .png .jpg and .pdf, we have have a confirmation from faculty and can use them freely in Swapify project.
![56378050_601332610277943_205455597464715264_n](https://user-images.githubusercontent.com/18141200/73571856-d0997d00-446f-11ea-97bd-1c77d709e76c.jpg)
![56177116_307231279971438_516383475616448512_n](https://user-images.githubusercontent.com/18141200/73571857-d0997d00-446f-11ea-8f00-6b15458f9025.png)
[Fri-k-1.pdf](https://github.com/fri-team/Swapify/files/4141275/Fri-k-1.pdf)

**Comment by reibek** [comment]
All checked comments have been included in #287 except last one.

**Comment by marektavac** [comment]
We can close. We accept actual solution. Point 5 is not relevant
