### ISSUE TITLE
Adding a block is not working

### ISSUE THREAD

**Issue by marektavac** [fri-team/Swapify#291]
I try to add a new block (click in the timetable), select subject name, and cvicenie, but it was not succesfull: "Prosim skuste to neskor"

- [x] Adding subjects
- [x] Fix autocomplete in Adding Form (already created in #302)
- [x] Fix pull requests for subjects (incorrect subjects are suggested)

**Comment by BranislavTvrdy** [comment]
Adding block now works, but autocomplete in Adding Form needs to be reworked.
At the current state, there seems to be problem with pulling subjects from server.
Incorrect subjects are suggested.

**Comment by BranislavTvrdy** [comment]
Autocomplete from #302 is fixed.
![autocomplete](https://user-images.githubusercontent.com/18141200/82454389-01023700-9ab2-11ea-9916-a971df3f3fd2.png)

**Comment by BranislavTvrdy** [comment]
After analysis of subjects we came to conclusion the list of subjects is correct. Additional subjects are requested from UNIZA subjects DB for other faculties to use.
Also subjects can now be searched without case sensitivity (as shown in screenshots below).

Before:
![WoutToLower](https://user-images.githubusercontent.com/18141200/82454845-91407c00-9ab2-11ea-9db3-879273907c39.png)

After:
![WithToLower](https://user-images.githubusercontent.com/18141200/82454870-969dc680-9ab2-11ea-86d0-166d5de5d0c9.png)

**Comment by BranislavTvrdy** [comment]
Closed and solved by #347 Merge pull request.
