### ISSUE TITLE
Current timetable doesn't correspont with its actual state.

### ISSUE THREAD

**Issue by reibek** [fri-team/Swapify#300]
**Estimated to 2**
It looks, like it somehow is taking timetable from other year. None of courses correspont with reality.

**Comment by BranislavTvrdy** [comment]
Slack comment: "Ahojte pozeral som sa na projekt, že prečo nám v podstate nič nefunguje a zistil som že je to v tom ako získavame dáta zo školskej API a pravdepodobne som našiel príčinu. Pri dotazovani na API sa ako parameter posiela školský rok, od nového roku sa tam posielal 2020, no to nie je správne a správne by malo byt 2019, taktiež parameter “semester” sa vkladá s apostrofmi, no mal by sa bez, aby fungoval správne. "

**Comment by PetraKinder** [comment]
Semester start calculation
