### ISSUE TITLE
Fix notification default text position

### ISSUE THREAD

**Issue by BranislavTvrdy** [fri-team/Swapify#312]
Text inside notification popup window is misaligned.

**Comment by fri-team** [comment]
Do you can add some picture here?

**Comment by PetraKinder** [comment]
I think he meant this 
![notification](https://user-images.githubusercontent.com/56397457/76518538-91dbe700-645f-11ea-9731-b9ed0801c79b.jpg)

**Comment by BranislavTvrdy** [comment]
This is now fixed in #312_Fix_notification_default_text_position
