### ISSUE TITLE
CI CD

### ISSUE THREAD

**Issue by reibek** [fri-team/Swapify#317]
**Estimated to 30**

- [x] create VM on AWS (with Ubuntu)
- [x] prepare VM for Docker images
- [x] dockerization of Swapify project
- [x] deploy Application docker image and run it
- [ ] create easy way for app deployment
- [x] make testing with Travis or similar

**Comment by fri-team** [comment]
What with that? No description

**Comment by reibek** [comment]
Implement Continous integration - continous delivery system to our project.
