### ISSUE TITLE
Edit subject timetable - frontend

### ISSUE THREAD

**Issue by bohusmarian** [fri-team/Swapify#32]
ACC:
- Student is able to add new block with click in timetable empty space
- Student can specify time, day, name, course (any, with suggestions) through dialog
- The same dialog can be used to edit existing block when click on edit icon in block informtion
- The studenent can drop block through icon in block information
- He can edit just his timetable

**Comment by ikim23** [comment]
This task is too big and too old, I am closing it and creating 3 smaller ones instead:
- #77 
- #78 
- #79
