### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by MatejKopera** [fri-team/Swapify#321]
Subtask of US: #317 

travis builds are currently failing and pull request passing without control

CI:
- [x] analyse usage of github actions
- [x] configure github actions
- [x] fix failing tests
- [ ] include automatic gui test
- [x] run build on commit
- [x] don't allow merge on fail
- [x] disable old travis

CD:
- [ ] prepare for deploy

**Comment by marektavac** [comment]
Think about possibility to move to github... To have everythonk on one place:
https://github.com/fri-team/Swapify/actions/new

**Comment by marektavac** [comment]
@marektavac prosim posli mi aj email potrebujem na autentifikaciu

**Comment by fri-team** [comment]
- completed workflow for CI build and tests
- few BE tests were commented and will be fixed in different story
- FE tests are temporary commented, because of automated gui test. FE and BE has to run, but BE wont run because of incorrect default mail settings in appsettings.json file
