### ISSUE TITLE
Test Add new subject

### ISSUE THREAD

**Issue by marektavac** [fri-team/Swapify#323]
1.	Študent klikne na „Plus icon“ pre pridanie predmetu v ľavom bočnom paneli zoznamu 
        predmetov
2.	Systém zobrazí modálne okno
   a.	   Systém vyzve študenta na zadanie názvu predmetu
   b.	   Študent napíše presný názov predmetu
   c.	   Pre vyhľadanie predmetu študent klikne na „vyhľadať“ 
   d.	   Systém vyhľadá predmet
   e.	   Systém zvýrazní možnosti, kam je možné predmet umiestniť a zároveň vyšedí súčasný
           rozvrh študenta
3.	Používateľ zvolí jednu z ponúkaných možností umiestnenia predmetu
   a.	   Po kliknutí na blok sa zobrazia detaily bloku
   b.	   V detaile bloku je ikonka „Add subject“
4.	Používateľ zaklikne ikonku „Add subject“
   a.	   Systém pridá predmet do rozvrhu užívateľa
      i.	V rozvrhu pribudne blok predmetu
      ii.	Predmet sa zobrazí v ľavom bočnom paneli 
5.	Systém vráti používateľa na home screen – jeho rozvrh

**Comment by BranislavTvrdy** [comment]
@PetraKinder Write test description for user story Add new subject (#315)

**Comment by PetraKinder** [comment]
[Testovacie scenáre.xlsx](https://github.com/fri-team/Swapify/files/4710284/Testovacie.scenare.xlsx)

**Comment by PetraKinder** [comment]
[Test Add new subject.docx](https://github.com/fri-team/Swapify/files/4710335/Test.Add.new.subject.docx)

**Comment by brano98** [comment]
Scenario was tested and no issues were found.
