### ISSUE TITLE
Check tests stability

### ISSUE THREAD

**Issue by reibek** [fri-team/Swapify#333]
**Estimated to 8**
Check tests stability for tests created for automated GUI tests.
Related to #311

**Comment by marektavac** [comment]
@reibek tazko povedat co sa tym myslelo, mozno len otetsovanie ze ci tie testy zaberaju...
Najprv testy splnenim (ked vsetko funguje) a potom si mozno nasimulovat rozne chybove stavy a ze ci ich tie testy odhalia...
Nic lepsie ma nenapadlo..
