### ISSUE TITLE
Db configuration for automated GUI tests

### ISSUE THREAD

**Issue by marektavac** [fri-team/Swapify#336]
To be able to create and run automated GUI test it is crucial to have some system state predefined..
It is possible to archive it with predefined mongo db ..
- [x] switch to testing db before start test
- [x] clean db after test

Is should work on developer machine same as testing server
Setup process how to manage the testing db (changing the schema and content) when necessary

Other possibility is to use mock classes

#332 depened on this

**Comment by Malwaare** [comment]
Closed
