### ISSUE TITLE
Dockerize swapify project

### ISSUE THREAD

**Issue by MarekZorvan** [fri-team/Swapify#338]
Add a **Dockerfile** at the root of the repo and set up your right project paths inside.

Subtask to US: #317

**Comment by marektavac** [comment]
It is used to have docker-compose.yml in the root and Dockerfile inside servers projects...

**Comment by MarekZorvan** [comment]
http works, but https is still not reachable. Probably some configuration inside docker for nginx is required for port 443.

http://18.184.180.36/

![image](https://user-images.githubusercontent.com/43585019/81390408-acf36c00-911b-11ea-91ad-f0df50f38851.png)

**Comment by fri-team** [comment]
You can move this https configuration to another task, if you don't know how to continue...
May be we can ask GL to help

**Comment by MarekZorvan** [comment]
https will need SSL certificate to run (will be done in another issue)

**Comment by MarekZorvan** [comment]
BE doesn't work, it failed during start because of MailSettings in .config which has empty settings for Mail and has to be changed before each start

**Comment by MarekZorvan** [comment]
FE + BE are running, but BE can't to reach mongo DB and exception is thrown

**Comment by fri-team** [comment]
what for exception? Do you can reach mongo manually?

**Comment by MarekZorvan** [comment]
Alright, it's fixed. Problem was in wrong container name and connection string.

Swapify works at http://18.184.180.36/

![image](https://user-images.githubusercontent.com/43585019/82652306-b1407e80-9c1d-11ea-9971-3dd5636806f3.png)

**Comment by MarekZorvan** [comment]
Code has to be cleaned from comments and merged with develop branch or create branch for aws deployment...

**Comment by MarekZorvan** [comment]
Routing for http was fixed upgrading to .net core 3.1

Email confirmation makes problems. It says invalid token, and when confirmation email should be resent, email sendign fails and throws invalid Uri exception. 
(Registration has been changed, if user registers with the same email, he should recieve confirmation email again, if not confirmed)
