### ISSUE TITLE
Create tutorial for creating of new automated test

### ISSUE THREAD

**Issue by reibek** [fri-team/Swapify#340]
Documentation.

**Comment by reibek** [comment]
Short tutorial documentation has been made and is available [here](https://drive.google.com/file/d/1P271f6OonxZ3ZSaoCk9xsIuqUSf-lDaS/view?usp=sharing).

**Comment by MarekZorvan** [comment]
You can add reference to this documentation for codeceptjs. 

https://docs.w3cub.com/codeceptjs/
