### ISSUE TITLE
Redirect from Reset password from email routes user to "/login" but React GUI window is not there (on AWS)

### ISSUE THREAD

**Issue by MarekZorvan** [fri-team/Swapify#366]
When you reset your password, you get link to password reset. You enter your new password, but when you are redirected from reset password to /login page, the GUI for login is missing.

After new password is confirmed:
![image](https://user-images.githubusercontent.com/43585019/95424735-66f93900-0943-11eb-8792-f7d030fba3be.png)

Login GUI is missing: (/login page in URL)
![image](https://user-images.githubusercontent.com/43585019/95424876-ab84d480-0943-11eb-8f8d-bc4815234d8c.png)

**Comment by reibek** [comment]
Problem was solved in pull request #377 . Funcionality was tested on localhost with correct mail settings.
