### ISSUE TITLE
Get Courses request returns undefined or empty response (on AWS only)

### ISSUE THREAD

**Issue by MarekZorvan** [fri-team/Swapify#367]
/api/timetable/course/getCoursesAutoComplete/Algorit doesn't return data...

Lines from the log:
![image](https://user-images.githubusercontent.com/43585019/95425299-5ac1ab80-0944-11eb-821c-3a649ea23000.png)

**Comment by MarekZorvan** [comment]
Throws this exception on aws when "app.UseDeveloperExceptionPage();" is used in Startup.cs

System.InvalidOperationException: Unable to resolve service for type 'MongoDB.Driver.IMongoDatabase' while attempting to activate 'FRITeam.Swapify.Backend.StudentService'.

**Comment by MarekZorvan** [comment]
MongoDB connection settings were fixed, but server returns empty response from MongoDB to Client with no errors.

The database is empty and it shouldn't be. Why are data not loaded on server but localhost works? Is it problem with some .json file missing or something is different during startup?

**Comment by marektavac** [comment]
1. Does it ever work already on AWS? (is it some problem, which happend during last doployments?)
2. Does our MongoDB work on AWS properly (other function - e.g. saving and reading this data)? 
3. If yes, what does it mean "why data are not loaded?" - what for data, when?

**Comment by MarekZorvan** [comment]
1. It has never worked on AWS (loading timetable using student's personal number or searching for subject)

2. MongoDB seems to be connected correctly now. It saves user and can load user's data(including timetable) and lets him login.

3. Subjects data are not in database, so it can't search for them and returns empty [] as result.


*Note: AWS application is currently turned off because development debugging is used in current production build.

**Comment by marektavac** [comment]
So it is not a problem of Mongo configuration... It looks like for me, there is a problem with connecting to UNIZA timetable API..
Also I remember, we have imported the list of all subject manually to the system... (uniza study program page was parsed, data extracted and imported to our system)

**Comment by MarekZorvan** [comment]
It can load timetables from API, but for subjects, there is no API used for connection, only search from the DB which is empty of course.

This returns data:

https://nic.uniza.sk/webservices/getUnizaScheduleContent.php?m=5&id=558888

I think, we are missing loading subject to our DB somewhere in the code.

**Comment by marektavac** [comment]
"I think, we are missing loading subjects to our DB somewhere in the code." - that is right... in my opinion

**Comment by marektavac** [comment]
There is some code: https://github.com/fri-team/Swapify/tree/develop/CoursesParser, for parsing the subjects... which will generate some json output with subjects to import to db...

**Comment by MarekZorvan** [comment]
The problem with subject data will be solved in #375
