### ISSUE TITLE
Set timetable with student personal number doesn't work (on AWS only)

### ISSUE THREAD

**Issue by MarekZorvan** [fri-team/Swapify#368]
/api/timetable/setStudentTimetableFromPersonalNumber doesn't work either timetable can't be loaded using student personal number...

**Comment by MarekZorvan** [comment]
Throws this exception on aws when "app.UseDeveloperExceptionPage();" is used in Startup.cs

System.InvalidOperationException: Unable to resolve service for type 'MongoDB.Driver.IMongoDatabase' while attempting to activate 'FRITeam.Swapify.Backend.StudentService'.

**Comment by MarekZorvan** [comment]
Startup.cs for production was missing MongoDB settings initialization.

New error has occured:

System.TimeoutException: A timeout occured after 30000ms selecting a server using CompositeServerSelector{ Selectors = 
MongoDB.Driver.MongoClient+AreSessionsSupportedServerSelector, LatencyLimitingServerSelector{ AllowedLatencyRange = 00:00:00.0150000 } }. Client view of cluster state is { ClusterId : "1", ConnectionMode : "Automatic", Type : "Unknown", State : "Disconnected", Servers : [{ ServerId: "{ ClusterId : 1, EndPoint : "Unspecified/localhost:27017" }", EndPoint: "Unspecified/localhost:27017", State: "Disconnected", Type: "Unknown", HeartbeatException: "MongoDB.Driver.MongoConnectionException: An exception occurred while opening a connection to the server.

**Comment by MarekZorvan** [comment]
MongoDB has been fixed and timetable successfully loads when student enters his personal number.

**Comment by marektavac** [comment]
What was the problem? Do you have fixed some code? (commit link)

**Comment by MarekZorvan** [comment]
MongoDB configuration in startup for client was missing for production build, so in result DB worked only for identification but not for other data, thus no timetable could be saved/loaded to the database.

**Comment by marektavac** [comment]
So this bug is fixed also.. If yes, you can close this (as duplicate?)
