### ISSUE TITLE
GitHub actions are blocking pull requests - one BE test is failing

### ISSUE THREAD

**Issue by MarekZorvan** [fri-team/Swapify#370]
One of the BE tests fails and prevents us from merging to develop branch. 

The test is probably incorrectly created and makes problems. Remove (comment out) the code or find appropriate fix to make it work

See the GitHub actions or run your tests locally to identify the wrong test.

![image](https://user-images.githubusercontent.com/43585019/95426730-aa08db80-0946-11eb-8fcb-8e53f8cc5e9b.png)

**Comment by BranislavTvrdy** [comment]
We fixed the mergingg problem in #367 branch.

**Comment by BranislavTvrdy** [comment]
We fixed the mergingg problem in #367 branch.

**Comment by BranislavTvrdy** [comment]
We fixed the mergingg problem in #367 branch.
