### ISSUE TITLE
Lecture can't be removed from student's timetable

### ISSUE THREAD

**Issue by MarekZorvan** [fri-team/Swapify#372]
![image](https://user-images.githubusercontent.com/43585019/95722886-ce312900-0c74-11eb-8d26-3ec4591ed0e3.png)

![image](https://user-images.githubusercontent.com/43585019/95723056-00db2180-0c75-11eb-97e5-794a86725f4b.png)

**Comment by MarekZorvan** [comment]
@marektavac What do you think about this feature? I suggest, that timetable customization is good feature.

**Comment by marektavac** [comment]
I'm not sure you want to disable removing lectures or enable it...
I think it is good idea to be able to fully manage my timetable - to remove it, especially when UNIZA source of data is not very good and there could be errors..

**Comment by MarekZorvan** [comment]
Yes, we want to enable removal of lectures to make the timetable more customizable. The trash icon is missing there. Next feature will be adding custom blocks to the timetable which are not present in courses from timetable API.

**Comment by CholujMartin** [comment]
This issue is waiting for merge request but i wanted to tell you that I changed min max length of block from 2 - 4 to 1 - 10 if u don't want this feature changed then just tell me.
