### ISSUE TITLE
Left panel subjects menu shows duplicate for one subject

### ISSUE THREAD

**Issue by MarekZorvan** [fri-team/Swapify#373]
Name for lectures and seminars are not differentiated?

![image](https://user-images.githubusercontent.com/43585019/95743584-478b4480-0c92-11eb-9431-bec22501b889.png)

**Comment by marektavac** [comment]
It is possible, if we miss list of subject in the system, it is created the same subject 2x times, so the problem is may be not in comparing the names for lecture and seminar, but that the same subject is created 2x

**Comment by brano98** [comment]
Solved. Issue was that uniza API was returning CourseName-s with spaces at the end. I added Triming to ResponseParser to fields CourseName and CourseShortcut. App was getting course from db by CourseName and if it did not find one it created new one. I changed it to get course by CourseShortcut. If it does not have CourseShortcut it gets it by CourseName.

**Comment by marektavac** [comment]
Good job, strange is it was the problem just on AWS :-)... 
Possible issue: probably we should clean the database (timetables and xourses) after each term...
@brano98 
do you can add such issue? (with this reason)

**Comment by brano98** [comment]
#381
