### ISSUE TITLE
Get all timetables to mongoDB at start pf application

### ISSUE THREAD

**Issue by Malwaare** [fri-team/Swapify#375]
Data from university timetable API are not loaded to the database (production MongoDB). 

- [x] 1. Find the difference or reason why Mongo2GO (localhost) has subjects in DB and MongoDB (production AWS) doesn't

- [x] 2. Implement function in BE Backend.CourseService.cs which collects all subjects data from timetable API and put them to database collection

- [x] 3.  Use the function in Startup.cs after DB is connected and test it (ask for upload to AWS EC2)

- [x] 4. Condition 1 - if subject exists, don't put it inside DB

- [x] 5. Condition 2. - if connection fails to timetable API, just write message and skip

**Comment by marektavac** [comment]
Why to solve something what already is done? There is in git project for parsing all students plan on uniza page, parse it and generate json with all courses, which is then necessary to import to mongodb...

**Comment by MarekZorvan** [comment]
CreateDbAsync function called in startup.cs for Develop imports courses data from .json file.

Create new function for Production for importing all courses data from timetable API.

![image](https://user-images.githubusercontent.com/43585019/96253021-289ef200-0fb3-11eb-84e3-ff43291a7a50.png)

**Comment by fri-team** [comment]
already done
