### ISSUE TITLE
Editing/Adding/Deleting functions not working

### ISSUE THREAD

**Issue by BranislavTvrdy** [fri-team/Swapify#388]
Editing/Adding/Deleting functions are not working in current develop branch. 
Last working commit of this functionality is at: 
"Merge pull request #343 from fri-team/#328_Display_Confirmation_After_Registration"
since then all the commits just make it more unfunctional, there were changes to FE and BE starting at:
"Merge pull request #344 from fri-team/#247_MailUs_Second"
If someone knows how to solve this issue please elaborate in issue.

Also in current develop branch, the Lectures changed to Laboratories somehow.
![obrázok](https://user-images.githubusercontent.com/18141200/97016054-8ea7ee00-154c-11eb-9321-e412ba51e2c9.png)

**Comment by BranislavTvrdy** [comment]
Funcion of the #374 was last working "Merge pull request #343 from fri-team/#328_Display_Confirmation_After_Registration",
until this issue is solved the #374 is on hold.

**Comment by MarekZorvan** [comment]
JSON from FE can't be converted by BE server:

![image](https://user-images.githubusercontent.com/43585019/97079619-d8004800-15f5-11eb-9047-cc13d2b4bc62.png)

**Comment by MarekZorvan** [comment]
Problem with all laboratory type was here.

![image](https://user-images.githubusercontent.com/43585019/97083136-80baa180-160e-11eb-9684-8dc717fb3709.png)

**Comment by MarekZorvan** [comment]
Add, Delete and Edit functions work as well

**Comment by MarekZorvan** [comment]
Add/Edit logic was handled by wrong property. It's been fixed.

**Comment by BranislavTvrdy** [comment]
Adding/Editing/Removing was fixed by #389 .
