### ISSUE TITLE
Wrong registration confirmation email

### ISSUE THREAD

**Issue by marektavac** [fri-team/Swapify#392]
When I tried to register I have received email (see the picture) without any link to confirm. I am using centrum.cz email box...

![image](https://user-images.githubusercontent.com/37049814/97227789-456acf00-17d6-11eb-9e5c-1cd815f116ca.png)

When I switch the display to html it was OK, but question is if every user will know that..

**Comment by coreggon11** [comment]
@marektavac skusal som reprodukovat, ale vsetko fungovalo ok, mozno kvoli prehlidacu? centrum.cz na chrome fungovalo

**Comment by marektavac** [comment]
I try it once again, and it was OK, so may be it was fixed with another issue..., You can close this bug. :-)

**Comment by fri-team** [comment]
already done
