### ISSUE TITLE
Wrong activation link

### ISSUE THREAD

**Issue by marektavac** [fri-team/Swapify#393]
When I register and click on activation link I get:

Táto stránka webu 18.193.17.141 sa nenašlaNa http://18.193.17.141/confirmEmail/f810440f-fb33-4c85-a0e6-788d5390acd8/CfDJ8Ar7tbwchB5Hq5i9fFSHRYDQRcxmLV5wwQEfihLyUoCw%2Bobo524iZ5Ql1uPvUF2MLpO9ln%2BHfSfLx4c6N5LlSIUsbkBuIGXUbxQ7VqxYprRMu3dd0cpRQ7%2BjBT72BabArd%2BBNnsu72EL9xXbqhH3Oex2SL9Jyj5S6dAxQmOdMxp6Gnit8cnqvoUDsD5dS2drz3UEg8VgG0nH9xy%2Bc%2FHLpClMTTllzET9sR8kPD07IVvOqLtAeJ%2BaLFfLSp3FAwGQVg%3D%3D sa nenašla žiadna webová stránka
HTTP ERROR 404

**Comment by MatejKopera** [comment]
![image](https://user-images.githubusercontent.com/56389586/97979662-d8f06100-1dcf-11eb-9ca1-8504e926c525.png)

**Comment by MarekZorvan** [comment]
I can confirm. The registration link doesn't work. Request couldn't reach the server. 404 NOT FOUND

![image](https://user-images.githubusercontent.com/43585019/97980093-88c5ce80-1dd0-11eb-9a98-0fc2034eb450.png)

**Comment by MarekZorvan** [comment]
Old comments from my old branch are in comments. I think I solved the same issue at the time. And it's back.

![image](https://user-images.githubusercontent.com/43585019/97984696-66837f00-1dd7-11eb-8c26-175a1ab29eb8.png)

**Comment by MarekZorvan** [comment]
Problem caused, because useSpa() in Startup.cs was temporarily commented and not tested. It is neccessary for production, otherwise pages like this won't be accessible.

**Comment by fri-team** [comment]
already done
