### ISSUE TITLE
Forgotten password function does not work

### ISSUE THREAD

**Issue by brano98** [fri-team/Swapify#400]
Email for forgotten password does not come and app also does not redirect correctly.

**Comment by MatejKopera** [comment]
same issue as #393
![image](https://user-images.githubusercontent.com/56389586/97980427-0db0e800-1dd1-11eb-8bfa-c17dd1c4ab14.png)

**Comment by MarekZorvan** [comment]
404: Request /set-new-password NOT FOUND.

Well, it doesn't exists in controller. But /setNewPassword exists.

**Comment by MarekZorvan** [comment]
It can't find the most paths from api. Timetable doesn't work either.

![image](https://user-images.githubusercontent.com/43585019/97988297-0e4f7b80-1ddd-11eb-995b-b9ff4a5a002b.png)

**Comment by MarekZorvan** [comment]
Problem caused, because useSpa() in Startup.cs was temporarily commented and not tested. It is neccessary for production, otherwise pages like this won't be accessible.
