### ISSUE TITLE
Unwanted change of subject upon edit

### ISSUE THREAD

**Issue by BranislavTvrdy** [fri-team/Swapify#402]
When subject is edited and other subjects with identical names are present, ti will use first found.
Needs to be revorked in BE.

<img width="1760" alt="bug" src="https://user-images.githubusercontent.com/69460412/97979522-9cbd0080-1dcf-11eb-8b35-84b34a0911eb.png">

**Comment by marektavac** [comment]
What solution do you want to use? Course should have unique identifier... (id?) If there are some duplicity, this is the error...
