### ISSUE TITLE
Study group selection

### ISSUE THREAD

**Issue by marektavac** [fri-team/Swapify#41]
After student succesfull registration he/she should specify his/her study group...
It can be specified as text field, with auto fill of already known groups.
Specified course should be validated through API. 
Handle also nor correct specified courses (depend on API result)
Show busy indicator, if communication with TAPI takes longer time...
Approved group should be stored to student and saved to db...
Output should be forwarded to his/her actual timetable

**Comment by marektavac** [comment]
@bohusmarian please create API for it ASAP #51 is blocked by this

**Comment by marektavac** [comment]
@martingranak sa zavazuje, ze dokonci do buduceho tyzdna... (merge do master)

**Comment by mdomdo0** [comment]
added error message after not existing study group

**Comment by marektavac** [comment]
@mdomdo0 , you should add #41 to commit message, to have a link to commit in this note (see above david commits)

**Comment by fri-team** [comment]
Done already
