### ISSUE TITLE
About us page is empty

### ISSUE THREAD

**Issue by marektavac** [fri-team/Swapify#412]
The page: http://18.193.17.141/aboutus doesn't contain any text...
 
Old one look like this:
![image](https://user-images.githubusercontent.com/37049814/98910517-93b0eb00-24c3-11eb-9132-d8dc6f97ad82.png)

**Comment by BranislavTvrdy** [comment]
On localhost it works properly. So maybe there's an older version on server ? 
![obrázok](https://user-images.githubusercontent.com/18141200/99371638-7616c380-28bf-11eb-99c5-1a542fb6a02e.png)

**Comment by marektavac** [comment]
So, we still don't have automatic deployment after merge request?

**Comment by BranislavTvrdy** [comment]
Until there's no automatic deployment hence information about what version is on server, I have no way of knowing where is the problem. The "About us" page is accesible via [URL](http://18.193.17.141/aboutus), but it doesn't render properly, yet on localhost it does.
![obrázok](https://user-images.githubusercontent.com/18141200/100037033-9f74a980-2e01-11eb-8d81-db238a1887b4.png)

**Comment by MarekZorvan** [comment]
See issue #405, but we have to test it on AWS to see if it affects this problem as well.

**Comment by CholujMartin** [comment]
It needs testing on AWS, bacause issue should be resolved with removing of additianal router
