### ISSUE TITLE
Reload on register is broken

### ISSUE THREAD

**Issue by CholujMartin** [fri-team/Swapify#415]
![obrázok](https://user-images.githubusercontent.com/72445676/99825196-fe62c600-2b56-11eb-9ff8-82f0f41ec34d.png)

A after refresh 

![obrázok](https://user-images.githubusercontent.com/72445676/99825503-66b1a780-2b57-11eb-9cee-7a40a6f37a32.png)

This issue is on both local and AWS

**Comment by MarekZorvan** [comment]
It's the same principle which @reibek used 1 year ago with Login page redirection. 

"Route to /register /login /aboutus has to lead to home page / and then the correct Component will be called by the rest of the route."
