### ISSUE TITLE
Welcome page

### ISSUE THREAD

**Issue by marektavac** [fri-team/Swapify#42]
Opening page for system should contain some welcome page, with basic information of functions of the system (profit for the student to use it). May be some tour of functions...

- [x] find some good solutions on internet
- [ ] specify out content
- [x] design it
- [x] implement

**Comment by ikim23** [comment]
* logo/timetable in the background
* 2 buttons: login & register (similar to trello)

**Comment by ikim23** [comment]
This is how I done it,  @marektavac what do you think?
> 
![capture](https://user-images.githubusercontent.com/22031712/39860272-68a1d16e-5445-11e8-9701-40e5ab7fa3c2.PNG)

**Comment by marektavac** [comment]
Parada :-)
