### ISSUE TITLE
Delete obsolute property IsLoaded in Course

### ISSUE THREAD

**Issue by brano98** [fri-team/Swapify#421]
Simply deleting this property doesnt solve this. Find solution how it can be done.
![210_error](https://user-images.githubusercontent.com/72451951/100354297-3a32db00-2ff0-11eb-90f0-cb5b9278bd3d.PNG)

**Comment by marektavac** [comment]
Is there some import from file? (it has to be fixed)
Are there already some data in DB with this property? - it should not be a problem, if yes it is necessary to modify the database...

**Comment by brano98** [comment]
There are no data in development db before first start. I just realized that if mongodb is not running and you start App this error doesnt appear. But I am not sure about production db.

**Comment by fri-team** [comment]
already done
