### ISSUE TITLE
Improvements in Add block form 

### ISSUE THREAD

**Issue by matusturjak** [fri-team/Swapify#445]
The goal is to make these improvements
- [x]  find a subject without writing accents
- [x]  pre-fill form windows
- [x] sort suggestion subjects by faculty

**Comment by marektavac** [comment]
what is happened when I change manually the time or day of the block in the form? Do you check once more the existence of the lecture in the course timetable? Or this is not so important?

**Comment by matusturjak** [comment]
> what is happened when I change manually the time or day of the block in the form? Do you check once more the existence of the lecture in the course timetable? Or this is not so important?

Now, If you changed time or day in the form it will do nothing. Personally i think it is not necessary to check it another time because if user wants to add block to another hour or day he can easily close form and click correct block in the timetable.
