### ISSUE TITLE
LDAP_login_doesn't_work_on_AWS

### ISSUE THREAD

**Issue by brano98** [fri-team/Swapify#465]
After I try to login using LDAP, 1-2 minute nothing happens and then blank page appears.

**Comment by CholujMartin** [comment]
Try to change "SecureSocketLayer": "false"na true in file appsettings.json. Or please try to login and post here server logs.

**Comment by brano98** [comment]
![image](https://user-images.githubusercontent.com/72451951/118836616-52f7bb80-b8c4-11eb-96a6-07a6013ef187.png)
[2021-05-19.log](https://github.com/fri-team/Swapify/files/6509810/2021-05-19.log)
Changing SecureSocketLayer does not solve the problem. It might be just bad redirection?? I also attached log and created branch 465_ldap you can use for testing which deploys this branch after pushing to github

**Comment by brano98** [comment]
TCP communication is now allowed. I provide you new logs.
[2021-05-31.log](https://github.com/fri-team/Swapify/files/6569654/2021-05-31.log)
