### ISSUE TITLE
SonarQube integration (server)

### ISSUE THREAD

**Issue by ZVARKO** [fri-team/Swapify#49]
Integration  SonarQube Scanner with Travis CI to inspect internal pull requests of repository and write comments on each line where issues are found.

**Comment by DenisaR1** [comment]
@ZVARKO  please provide more details / current status

**Comment by ZVARKO** [comment]
@DenisaR1 done

**Comment by ZVARKO** [comment]
Everything is done except pull request analysis. See #141.
