### ISSUE TITLE
Provide access to AWS

### ISSUE THREAD

**Issue by ikim23** [fri-team/Swapify#53]
1. Elastic Beanstalk - 2 environments (stage/prod) running on t2.micro EC2 instance
2. EC2 (for MongoDB) - one t2.micro EC2 instance, where we install MongoDB (single node) ourselves

**Comment by DenisaR1** [comment]
@tkurat please find out contact to @ikim23  and possibilities

**Comment by DenisaR1** [comment]
@tkurat  find out possibilites for staging / production server from GL
