### ISSUE TITLE
Create CI/CD for staging

### ISSUE THREAD

**Issue by brano98** [fri-team/Swapify#539]
create github action yaml file
	- solve docker versions
- create docker-compose-stg file
- solve version labeling, to reverse version in production + release -fixes and master - deployment branch (maybe)

Change autodeploy for stg
For stg use different ports and image version
Production will be triggered manually

**Comment by marektavac** [comment]
If there will be special branch for release (master), it can be deployed automaticaly after merge from stage or some bugfix, or is it too risky to make it automaticaly?

**Comment by marektavac** [comment]
docker versions should be ideally somehow connected with server application version

**Comment by brano98** [comment]
AWS is prepared for staging (available ports 81, 444) and I also created nginx config.
[nginx_stg.conf.txt](https://github.com/fri-team/Swapify/files/7844338/nginx_stg.conf.txt)
