### ISSUE TITLE
Change popup text when incorrect login

### ISSUE THREAD

**Issue by Flacore** [fri-team/Swapify#584]
*Change text for email login
*Change text for student login
+ announcement about changing login method to Uniza LDAP instead of Fri LDAP

**Comment by Flacore** [comment]
visualization before committing changes need to be reviewed

**Comment by Flacore** [comment]
**_I'm adding some of my ideas for changes. Left site of every picture is new idea and right site is how it's look right now._**

For e-mail login i change text notification which pop up after bad login and because we planning to migrate to Uniza LDAP i also change text for switching login method.
![Email ](https://user-images.githubusercontent.com/44835476/166210310-b3f7b219-6803-4788-91da-e5c9f9921210.png)

For ldap login i change popup text to be more precise and describe more potential error from user site.
![Ldap](https://user-images.githubusercontent.com/44835476/166210312-52c4ff6f-28eb-4965-b6e4-f3485551e935.png)

And last i create my idea of notification for big changes in system.  
![Swapify ](https://user-images.githubusercontent.com/44835476/166210317-a80db81f-7d57-4b39-89a4-1727235aecf2.png)

@Rado996 , @marektavac if you have time i would be glad for yours feedback what you think about this potential changes.

**Comment by marektavac** [comment]
Myslim, ze moze byt... Mozno do toho oznamu pridat, ze ak uz bol prihlaseny jeho ucet je zachovany, staci pouzit heslo pre vzdelavanie.uniza.sk alebo nieco take..
Co ty na to z pohladdu uzivatela @ondrejkasaj ?
