### ISSUE TITLE
API call for subject time table is not working

### ISSUE THREAD

**Issue by Rado996** [fri-team/Swapify#594]
API call for subject time table is not working because we were call API with data based on course code, course codes has been changed but API call parameters has not. We have to specify API call parameters based on faculty. 

For course code 6II0025, second parameter is 6 but it should be 5 because FRI faculty is identified by 5
 https://nic.uniza.sk/webservices/getUnizaScheduleContent.php?m=4&id=6II0025,6,1,2&r=2022&s=Z
 
 This is correct
 https://nic.uniza.sk/webservices/getUnizaScheduleContent.php?m=4&id=6II0025,5,1,2&r=2022&s=Z

**Comment by marektavac** [comment]
@Rado996 how does it look? I Thought it is already finished...

**Comment by Rado996** [comment]
Fix for the issue is ready but as i said yesterday on our meeting, i am having trouble with reverting ldap pull request, i have to look deeper into what is there and what i have to change, i was hoping that revert of pull request will take develop branch to state before university ldap merge but it looks like something from university ldap branch is still remaining in develop branch.
