### ISSUE TITLE
[Event] design of window with new custom event

### ISSUE THREAD

**Issue by barbierikovadom** [fri-team/Swapify#607]
Design the new pop-up window for adding a new custom event to the timetable

**Comment by PatrikCader27** [comment]
Some designs of the new pop-up window we discussed at the last meeting.

The first one is with a slider to choose between the school or custom event. The second one is to choose the type of event from the options which would cause to change the window dynamically.

**The group made a consensual decision to go with the first option.**

<img width="500" alt="custom_event_popup" src="https://user-images.githubusercontent.com/117161026/199383512-861a1819-2451-4a5b-ae8b-5272a817777c.png">
