### ISSUE TITLE
[Teacher] update of model

### ISSUE THREAD

**Issue by barbierikovadom** [fri-team/Swapify#609]
- [x] Analyze application and database for integration of new type of user: Teacher (similar as Student)
- [x] Refactor entity that stores data for timetable to be more general
- [x] Implement possibility to show blocked hours for teacher timetable (Backend)
- [x] Implement button to choose if blocked hours can be vissible (Frontend)
- [x] Implement types of timetables (student, teacher, unknown)
- [x] Ensure that teacher cannot request for course change

**Comment by MichalMurin** [comment]
![Screenshot 2022-11-09 181939](https://user-images.githubusercontent.com/62663409/200912089-03f0498a-851d-4b55-ad1e-f9119e2b0c1a.png)

- First result after loading blocked hours from teacher timetable
