### ISSUE TITLE
Redesign of login page

### ISSUE THREAD

**Issue by barbierikovadom** [fri-team/Swapify#624]
Create new version of login page.
Some ideas from students:
- font
- different possition for reCaptcha
- make lines for name and password smaller
- timetable in colors of FRI or UNIZA
- better contrast of font and background
- better position for button for logining with email or forgetting password

**Comment by marektavac** [comment]
Calculate with Office 365 authentication

**Comment by PatrikCader27** [comment]
<img width="581" alt="Screenshot 2022-11-24 at 08 42 41" src="https://user-images.githubusercontent.com/117161026/203722594-d34c950b-438b-4fff-9517-d4d62f5cb3f6.png">
First version

**Comment by PatrikCader27** [comment]
https://www.figma.com/file/EerGKcJdHSoYmiee0ld9O8/Swapify---login-page?node-id=205%3A31&t=GcnegDP5qU8IOo4h-0

**Comment by marektavac** [comment]
Very nice, big progress on start page... @PatrikCader27 Save here also old one page, to be able to compare versions on panel stroy

**Comment by PatrikCader27** [comment]
Screenshot of the newest version with updated graphics (available to check in figma with previously posted link) 
<img width="736" alt="Screenshot 2022-12-01 at 02 06 19" src="https://user-images.githubusercontent.com/117161026/204941192-7660546a-fd6f-463d-8cc2-2c8cbff17f0a.png">

Screenshot of the old version for comparison. 
<img width="1346" alt="Screenshot 2022-12-01 at 02 08 32" src="https://user-images.githubusercontent.com/117161026/204941473-c2d9ca8b-7c7e-4ed4-a52f-0de3efc2dedd.png">
