### ISSUE TITLE
Cursor not visible in "Napíšte nám" window - STAGING

### ISSUE THREAD

**Issue by MichalMurin** [fri-team/Swapify#634]
Tested on staging: (https://swapify.fri.uniza.sk:444/)
Steps to reproduce:

1. Click on the top right panel to the "Napíšte nám" icon
2. The windows for the message is shown
3. When I drag my cursor to the window, it is not visible

**Comment by PeterKulas** [comment]
I wanted to fix this bug, but i see cursor.

**Comment by MichalMurin** [comment]
It is probably happening only in dark mode.
When the window is dark, cursor in text boxes has the same color and it is not visible.

**Comment by PeterKulas** [comment]
Yes you are right, I'm going to check it out.
