### ISSUE TITLE
Allow user to remove block

### ISSUE THREAD

**Issue by ikim23** [fri-team/Swapify#77]
As a student I want to remove blocks form my timetable so that I need a functionality for this.

**Comment by DenisaR1** [comment]
@dobi28  Please complete this task until 6.12.

**Comment by davidm1766** [comment]
![image](https://user-images.githubusercontent.com/26389312/49207674-ea47bc00-f3b5-11e8-99ad-85bba79e68d4.png)
Just active this button

**Comment by fri-team** [comment]
Done already
