### ISSUE TITLE
Allow user to add new block

### ISSUE THREAD

**Issue by ikim23** [fri-team/Swapify#78]
As a student I want to add a new block so that I need develop functionailty for this.

**Comment by martingranak** [comment]
bolo naimplementovane kliknutie na prazdny blok, dá sa identifikovať, na ktorý blok sa kliklo

**Comment by DenisaR1** [comment]
@mdomdo0  The task must be done (that means after review). Please complete the task until 6.12 (next meeting).

**Comment by martingranak** [comment]
After click to empty block show dialog window (block detail) with room, lector (not mandatory) and length or start-end.
On hover show "+" with 1s delay.

**Comment by fri-team** [comment]
Done already
