### ISSUE TITLE
Allow user to edit existing block

### ISSUE THREAD

**Issue by ikim23** [fri-team/Swapify#79]

**Comment by DenisaR1** [comment]
@martingranak please find out the actual state

**Comment by DenisaR1** [comment]
please provide current status of implementation

**Comment by martingranak** [comment]
This feature is not implemented.
It is necessary to add edit icon to block detail. After click on this icon user will open form for editing block. Form should be similar as form for adding new block. In this fom will be current data of this block. Submit button will update data of this block.

**Comment by martingranak** [comment]
@mdomdo0 what is a current status of your part of this task?

**Comment by fri-team** [comment]
Done already
